CREATE DATABASE khattarnelli_db;

use khattarnelli_db;

CREATE TABLE productos (
  id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL,
  precio NUMERIC(16,6) NOT NULL,
  descripcion VARCHAR(100) NOT NULL,
  imagen VARCHAR(200) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pedidos (
    id INT(20) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    total NUMERIC(20,6) NOT NULL,
    productos VARCHAR(200) NOT NULL,
    ubicacion VARCHAR (100) NOT NULL,
    correo VARCHAR(50) NOT NULL,
    telefono VARCHAR (50) NOT NULL,
    metodo_de_pago VARCHAR (50) NOT NULL,
    estado VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE detalle_pedido(
    id INT(20) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    pedido_id INT(20) UNSIGNED NOT NULL, 
    producto_id INT(11) UNSIGNED NOT NULL, 
    cantidad INT(5) UNSIGNED NOT NULL,
    precio_unitario NUMERIC(16,4) NOT NULL,
    FOREIGN KEY (pedido_id) REFERENCES pedidos(id) ON DELETE CASCADE,
    FOREIGN KEY (producto_id) REFERENCES productos(id) ON DELETE RESTRICT
);

CREATE TABLE usuarios (
    id INT(20) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    passw VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
